pipeline {
    agent any

    stages {
        
        stage ('Build') {
            steps {
                dir('src\\Jenkins.CICD\\Jenkins.CICD') {
                    bat 'dotnet build '
                }
            }
        }

        stage ('Test') {
            steps {
                dir('src\\Jenkins.CICD\\Jenkins.CICD.Test') {
                    bat 'dotnet test --collect:"XPlat Code Coverage" '
                }
            }
        }

        stage ('Sonar analysis') {
            
            environment {
                scannerHome = tool "SONAR_SCANNER"
            }

            steps {
                withSonarQubeEnv('SONAR_LOCAL') {
                    bat '${scannerHome}/bin/sonar-scanner -e -Dsonar.projectKey=JenkinsCICD -dsonar .host.url=http://localhost:90000 -Dsonar.login=e378f35eabd51a38ce106b64f5d4c70515b7431f -D .coverage.exclusions=**/ClientApp/**'
                }
            }
        }
        
        stage ('Fim') {
            steps {
                bat 'echo fim'
            }
        }
        
    }
}