pipeline {
    agent any

    stages {
        
        stage ('Build') {
            steps {
                bat '
                cd src\\Jenkins.CICD\\Jenkins.CICD
                dotnet build
                '
            }
        }
        
        stage ('Meio') {
            steps {
                bat 'echo meio'
                sleep(5)
            }
        }
        
        stage ('Fim') {
            steps {
                bat 'echo fim'
            }
        }
        
    }
}